### ISSUE TITLE
Suggestion: Use system dll for icon

### ISSUE THREAD

**Issue by mileso** [ccchan234/LaunchQE#1]
When I ran the script, it initially failed because I had not downloaded the icon file `tool-icon-8075-Windows.ico` from the repo (I could have sworn I only saw three files in the repo 🤷).  I know this will only work for Windows, but I found it convenient to use a system .dll for icons to eliminate dependencies on separate icon files.

For example:
`Menu, Tray, Icon, %A_winDir%\System32\shell32.dll, 160`

**Comment by ccchan234** [comment]
up to any users.
